version: '3.8'

services:

  
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: geos-ui_prod
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASSWD}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
      
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - "discovery.type=single-node"

volumes:
  postgres_data: