apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    graph-geos.service: postgres-data
  name: postgres-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
